insert into USUARIO( ID, LOGIN, SENHA )
values( 1, 'admin', 'admin' ); 

INSERT INTO PRODUTO( ID, DESCRICAO, NOME, PRECO)
VALUES( PRODUTO_SEQ.nextval, 'ENTREGA RÁPIDA', 'Teste', 23.23 );

INSERT INTO NOTA_FISCAL( id, data, cnpj )
VALUES( NOTA_FISCAL_SEQ.NEXTVAL, to_date('29/08/2014','dd/mm/yyyy'), '16-726-059/0001-00' );

INSERT INTO ITEM( ID, QUANTIDADE, VALOR_UNITARIO, NOTAFISCAL_ID, PRODUTO_ID )
VALUES( ITEM_SEQ.NEXTVAL, 2, 250.23, NOTA_FISCAL_SEQ.CURRVAL, PRODUTO_SEQ.CURRVAL );

INSERT INTO PRODUTO( ID, DESCRICAO, NOME, PRECO)
VALUES( PRODUTO_SEQ.nextval, 'LOJA VIRTUAL', 'Teste', 150.23 );

INSERT INTO NOTA_FISCAL( id, data, cnpj )
VALUES( NOTA_FISCAL_SEQ.NEXTVAL, to_date('28/08/2014','dd/mm/yyyy'), '05.167.338/0001-56' );

INSERT INTO ITEM( ID, QUANTIDADE, VALOR_UNITARIO, NOTAFISCAL_ID, PRODUTO_ID )
VALUES( ITEM_SEQ.NEXTVAL, 1, 250.23, NOTA_FISCAL_SEQ.CURRVAL, PRODUTO_SEQ.CURRVAL );

INSERT INTO ITEM( ID, QUANTIDADE, VALOR_UNITARIO, NOTAFISCAL_ID, PRODUTO_ID )
VALUES( ITEM_SEQ.NEXTVAL, 10, 100.23, NOTA_FISCAL_SEQ.CURRVAL, PRODUTO_SEQ.CURRVAL );

INSERT INTO NOTA_FISCAL( id, data, cnpj )
VALUES( NOTA_FISCAL_SEQ.NEXTVAL, to_date('27/08/2014','dd/mm/yyyy'), '05.167.338/0001-56' );

INSERT INTO ITEM( ID, QUANTIDADE, VALOR_UNITARIO, NOTAFISCAL_ID, PRODUTO_ID )
VALUES( ITEM_SEQ.NEXTVAL, 3, 2.23, NOTA_FISCAL_SEQ.CURRVAL, PRODUTO_SEQ.CURRVAL );

INSERT INTO ITEM( ID, QUANTIDADE, VALOR_UNITARIO, NOTAFISCAL_ID, PRODUTO_ID )
VALUES( ITEM_SEQ.NEXTVAL, 4, 20.23, NOTA_FISCAL_SEQ.CURRVAL, PRODUTO_SEQ.CURRVAL );

INSERT INTO NOTA_FISCAL( id, data, cnpj )
VALUES( NOTA_FISCAL_SEQ.NEXTVAL, to_date('26/08/2014','dd/mm/yyyy'), '16-726-059/0001-00' );

INSERT INTO ITEM( ID, QUANTIDADE, VALOR_UNITARIO, NOTAFISCAL_ID, PRODUTO_ID )
VALUES( ITEM_SEQ.NEXTVAL, 3, 2.23, NOTA_FISCAL_SEQ.CURRVAL, PRODUTO_SEQ.CURRVAL );

INSERT INTO ITEM( ID, QUANTIDADE, VALOR_UNITARIO, NOTAFISCAL_ID, PRODUTO_ID )
VALUES( ITEM_SEQ.NEXTVAL, 4, 20.23, NOTA_FISCAL_SEQ.CURRVAL, PRODUTO_SEQ.CURRVAL );

INSERT INTO NOTA_FISCAL( id, data, cnpj )
VALUES( NOTA_FISCAL_SEQ.NEXTVAL, to_date('25/08/2014','dd/mm/yyyy'), '05.167.338/0001-56' );

INSERT INTO ITEM( ID, QUANTIDADE, VALOR_UNITARIO, NOTAFISCAL_ID, PRODUTO_ID )
VALUES( ITEM_SEQ.NEXTVAL, 30, 251263.23, NOTA_FISCAL_SEQ.CURRVAL, PRODUTO_SEQ.CURRVAL );

INSERT INTO ITEM( ID, QUANTIDADE, VALOR_UNITARIO, NOTAFISCAL_ID, PRODUTO_ID )
VALUES( ITEM_SEQ.NEXTVAL, 40, 7853366.23, NOTA_FISCAL_SEQ.CURRVAL, PRODUTO_SEQ.CURRVAL );

INSERT INTO PRODUTO( ID, DESCRICAO, NOME, PRECO)
VALUES( PRODUTO_SEQ.nextval, 'EAD', 'Teste', 250.23 );

INSERT INTO NOTA_FISCAL( id, data, cnpj )
VALUES( NOTA_FISCAL_SEQ.NEXTVAL, to_date('24/08/2014','dd/mm/yyyy'), '16-726-059/0001-00' );

INSERT INTO ITEM( ID, QUANTIDADE, VALOR_UNITARIO, NOTAFISCAL_ID, PRODUTO_ID )
VALUES( ITEM_SEQ.NEXTVAL, 10, 2263.23, NOTA_FISCAL_SEQ.CURRVAL, PRODUTO_SEQ.CURRVAL );

INSERT INTO ITEM( ID, QUANTIDADE, VALOR_UNITARIO, NOTAFISCAL_ID, PRODUTO_ID )
VALUES( ITEM_SEQ.NEXTVAL, 50, 5366.23, NOTA_FISCAL_SEQ.CURRVAL, PRODUTO_SEQ.CURRVAL );

INSERT INTO NOTA_FISCAL( id, data, cnpj )
VALUES( NOTA_FISCAL_SEQ.NEXTVAL, to_date('23/08/2014','dd/mm/yyyy'), '05.167.338/0001-56' );

INSERT INTO ITEM( ID, QUANTIDADE, VALOR_UNITARIO, NOTAFISCAL_ID, PRODUTO_ID )
VALUES( ITEM_SEQ.NEXTVAL, 10, 233.23, NOTA_FISCAL_SEQ.CURRVAL, PRODUTO_SEQ.CURRVAL );

INSERT INTO ITEM( ID, QUANTIDADE, VALOR_UNITARIO, NOTAFISCAL_ID, PRODUTO_ID )
VALUES( ITEM_SEQ.NEXTVAL, 5, 166.23, NOTA_FISCAL_SEQ.CURRVAL, PRODUTO_SEQ.CURRVAL );

INSERT INTO ITEM( ID, QUANTIDADE, VALOR_UNITARIO, NOTAFISCAL_ID, PRODUTO_ID )
VALUES( ITEM_SEQ.NEXTVAL, 6, 9663.23, NOTA_FISCAL_SEQ.CURRVAL, PRODUTO_SEQ.CURRVAL );

INSERT INTO ITEM( ID, QUANTIDADE, VALOR_UNITARIO, NOTAFISCAL_ID, PRODUTO_ID )
VALUES( ITEM_SEQ.NEXTVAL, 8, 856.23, NOTA_FISCAL_SEQ.CURRVAL, PRODUTO_SEQ.CURRVAL );

INSERT INTO ITEM( ID, QUANTIDADE, VALOR_UNITARIO, NOTAFISCAL_ID, PRODUTO_ID )
VALUES( ITEM_SEQ.NEXTVAL, 10, 5663.23, NOTA_FISCAL_SEQ.CURRVAL, PRODUTO_SEQ.CURRVAL );

INSERT INTO ITEM( ID, QUANTIDADE, VALOR_UNITARIO, NOTAFISCAL_ID, PRODUTO_ID )
VALUES( ITEM_SEQ.NEXTVAL, 9, 2366.23, NOTA_FISCAL_SEQ.CURRVAL, PRODUTO_SEQ.CURRVAL );

